app = "n8n-app"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  N8N_BASIC_AUTH_ACTIVE="true"
  N8N_BASIC_AUTH_USER="admin"
  N8N_BASIC_AUTH_PASSWORD="super78784888"
  N8N_HOST="n8n-app.fly.dev"
  N8N_PORT="5678"
